// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WargameBoard.Core.Data;

#nullable disable

namespace WargameBoard.Web.Migrations
{
    [DbContext(typeof(WargameDbContext))]
    [Migration("20250913190306_OPOP")]
    partial class OPOP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WargameBoard.Core.Entities.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.BoardCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int?>("HexId")
                        .HasColumnType("int");

                    b.Property<int?>("LastStrength")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastStrengthUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("SensorAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Threshold")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("HexId");

                    b.ToTable("BoardCells");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.FortificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FortificationTypes");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Hex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KeyFeature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<int?>("TerrainTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerrainTypeId");

                    b.HasIndex("Q", "R")
                        .IsUnique();

                    b.ToTable("Hexes");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.HexFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureKind")
                        .HasColumnType("int");

                    b.Property<int?>("FortificationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("HexId")
                        .HasColumnType("int");

                    b.Property<int?>("ObstacleTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FortificationTypeId");

                    b.HasIndex("HexId");

                    b.HasIndex("ObstacleTypeId");

                    b.HasIndex("SideId");

                    b.ToTable("HexFeatures");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.MoveEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromHexId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToHexId")
                        .HasColumnType("int");

                    b.Property<int>("TokenPieceId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromHexId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ToHexId");

                    b.HasIndex("TokenPieceId");

                    b.HasIndex("TurnId");

                    b.ToTable("MoveEvents");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.MovementProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatAdvanceKmph")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoadKmph")
                        .HasColumnType("int");

                    b.Property<int>("XCountryKmph")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovementProfiles");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ObjectiveControlLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GainedLost")
                        .HasColumnType("int");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TurnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SideId");

                    b.HasIndex("TurnId");

                    b.ToTable("ObjectiveControlLogs");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ObstacleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ObstacleTypes");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Placement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HexId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlacedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("TokenPieceId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HexId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenPieceId");

                    b.HasIndex("TurnId");

                    b.ToTable("Placements");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxTurns")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TurnLengthMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Weather")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ScenarioObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionKind")
                        .HasColumnType("int");

                    b.Property<int>("HexId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("SideId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnThreshold")
                        .HasColumnType("int");

                    b.Property<int>("VictoryPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HexId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("SideId");

                    b.ToTable("ScenarioObjectives");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ScenarioUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int>("Posture")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("StartHexId")
                        .HasColumnType("int");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("StartHexId");

                    b.HasIndex("UnitId");

                    b.ToTable("ScenarioUnits");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentSideId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSideId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.SessionAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("HexFeatureId")
                        .HasColumnType("int");

                    b.Property<int?>("ScenarioObjectiveId")
                        .HasColumnType("int");

                    b.Property<int?>("ScenarioUnitId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("TokenPieceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HexFeatureId");

                    b.HasIndex("ScenarioObjectiveId");

                    b.HasIndex("ScenarioUnitId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenPieceId");

                    b.ToTable("SessionAssignments");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Side", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sides");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TerrainType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("DefenseModifier")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MovementCost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TerrainTypes");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TokenDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultSideId")
                        .HasColumnType("int");

                    b.Property<decimal>("HeightMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TokenGroupId")
                        .HasColumnType("int");

                    b.Property<decimal>("WidthMm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSideId");

                    b.HasIndex("TokenGroupId");

                    b.ToTable("TokenDesigns");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TokenGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DefaultHeightMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultWidthMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TokenGroups");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TokenPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HardwareIdentity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("bit");

                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SideId")
                        .HasColumnType("int");

                    b.Property<int>("TokenDesignId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HardwareIdentity")
                        .IsUnique()
                        .HasFilter("[HardwareIdentity] IS NOT NULL");

                    b.HasIndex("SideId");

                    b.HasIndex("TokenDesignId");

                    b.ToTable("TokenPieces");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TouchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardCellId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardCellId");

                    b.HasIndex("SessionId");

                    b.ToTable("TouchEvents");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cohesion")
                        .HasColumnType("int");

                    b.Property<int?>("MovementProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Personnel")
                        .HasColumnType("int");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("SideId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("VehiclesPrimary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovementProfileId");

                    b.HasIndex("SideId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.UnitCapability", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int?>("AtgmCount")
                        .HasColumnType("int");

                    b.Property<int>("AttackHard")
                        .HasColumnType("int");

                    b.Property<int>("AttackSoft")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int?>("HmgCount")
                        .HasColumnType("int");

                    b.Property<int>("IndirectSupport")
                        .HasColumnType("int");

                    b.Property<int?>("MortarsCount")
                        .HasColumnType("int");

                    b.Property<int?>("RocketsCount")
                        .HasColumnType("int");

                    b.HasKey("UnitId");

                    b.ToTable("UnitCapabilities");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UnitTypes");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.BoardCell", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Board", "Board")
                        .WithMany("Cells")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Hex", "Hex")
                        .WithMany("BoardCells")
                        .HasForeignKey("HexId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Board");

                    b.Navigation("Hex");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Hex", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.TerrainType", "TerrainType")
                        .WithMany()
                        .HasForeignKey("TerrainTypeId");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.HexFeature", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.FortificationType", "FortificationType")
                        .WithMany("HexFeatures")
                        .HasForeignKey("FortificationTypeId");

                    b.HasOne("WargameBoard.Core.Entities.Hex", "Hex")
                        .WithMany("HexFeatures")
                        .HasForeignKey("HexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.ObstacleType", "ObstacleType")
                        .WithMany("HexFeatures")
                        .HasForeignKey("ObstacleTypeId");

                    b.HasOne("WargameBoard.Core.Entities.Side", "Side")
                        .WithMany("HexFeatures")
                        .HasForeignKey("SideId");

                    b.Navigation("FortificationType");

                    b.Navigation("Hex");

                    b.Navigation("ObstacleType");

                    b.Navigation("Side");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.MoveEvent", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Hex", "FromHex")
                        .WithMany("MoveEventsFrom")
                        .HasForeignKey("FromHexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Session", "Session")
                        .WithMany("MoveEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Hex", "ToHex")
                        .WithMany("MoveEventsTo")
                        .HasForeignKey("ToHexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.TokenPiece", "TokenPiece")
                        .WithMany()
                        .HasForeignKey("TokenPieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Turn", "Turn")
                        .WithMany("MoveEvents")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromHex");

                    b.Navigation("Session");

                    b.Navigation("ToHex");

                    b.Navigation("TokenPiece");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ObjectiveControlLog", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.ScenarioObjective", "Objective")
                        .WithMany("Logs")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Session", "Session")
                        .WithMany("ObjectiveLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Side", "Side")
                        .WithMany()
                        .HasForeignKey("SideId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Turn", "Turn")
                        .WithMany("ObjectiveLogs")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Objective");

                    b.Navigation("Session");

                    b.Navigation("Side");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Placement", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Hex", "Hex")
                        .WithMany("Placements")
                        .HasForeignKey("HexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Session", "Session")
                        .WithMany("Placements")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.TokenPiece", "TokenPiece")
                        .WithMany()
                        .HasForeignKey("TokenPieceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Turn", "Turn")
                        .WithMany("Placements")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Hex");

                    b.Navigation("Session");

                    b.Navigation("TokenPiece");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ScenarioObjective", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Hex", "Hex")
                        .WithMany("ScenarioObjectives")
                        .HasForeignKey("HexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Scenario", "Scenario")
                        .WithMany("ScenarioObjectives")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Side", "Side")
                        .WithMany()
                        .HasForeignKey("SideId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hex");

                    b.Navigation("Scenario");

                    b.Navigation("Side");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ScenarioUnit", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Scenario", "Scenario")
                        .WithMany("ScenarioUnits")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Hex", "StartHex")
                        .WithMany("ScenarioUnits")
                        .HasForeignKey("StartHexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("StartHex");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Session", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Side", "CurrentSide")
                        .WithMany()
                        .HasForeignKey("CurrentSideId");

                    b.HasOne("WargameBoard.Core.Entities.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentSide");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.SessionAssignment", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.HexFeature", "HexFeature")
                        .WithMany()
                        .HasForeignKey("HexFeatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WargameBoard.Core.Entities.ScenarioObjective", "ScenarioObjective")
                        .WithMany()
                        .HasForeignKey("ScenarioObjectiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WargameBoard.Core.Entities.ScenarioUnit", "ScenarioUnit")
                        .WithMany()
                        .HasForeignKey("ScenarioUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WargameBoard.Core.Entities.Session", "Session")
                        .WithMany("Assignments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.TokenPiece", "TokenPiece")
                        .WithMany()
                        .HasForeignKey("TokenPieceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HexFeature");

                    b.Navigation("ScenarioObjective");

                    b.Navigation("ScenarioUnit");

                    b.Navigation("Session");

                    b.Navigation("TokenPiece");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TokenDesign", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Side", "DefaultSide")
                        .WithMany()
                        .HasForeignKey("DefaultSideId");

                    b.HasOne("WargameBoard.Core.Entities.TokenGroup", "TokenGroup")
                        .WithMany()
                        .HasForeignKey("TokenGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultSide");

                    b.Navigation("TokenGroup");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TokenPiece", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Side", "Side")
                        .WithMany()
                        .HasForeignKey("SideId");

                    b.HasOne("WargameBoard.Core.Entities.TokenDesign", "TokenDesign")
                        .WithMany()
                        .HasForeignKey("TokenDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Side");

                    b.Navigation("TokenDesign");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.TouchEvent", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.BoardCell", "BoardCell")
                        .WithMany()
                        .HasForeignKey("BoardCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.Session", "Session")
                        .WithMany("TouchEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardCell");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Turn", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Session", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Unit", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.MovementProfile", "MovementProfile")
                        .WithMany()
                        .HasForeignKey("MovementProfileId");

                    b.HasOne("WargameBoard.Core.Entities.Side", "Side")
                        .WithMany()
                        .HasForeignKey("SideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WargameBoard.Core.Entities.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovementProfile");

                    b.Navigation("Side");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.UnitCapability", b =>
                {
                    b.HasOne("WargameBoard.Core.Entities.Unit", "Unit")
                        .WithOne("Capability")
                        .HasForeignKey("WargameBoard.Core.Entities.UnitCapability", "UnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Board", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.FortificationType", b =>
                {
                    b.Navigation("HexFeatures");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Hex", b =>
                {
                    b.Navigation("BoardCells");

                    b.Navigation("HexFeatures");

                    b.Navigation("MoveEventsFrom");

                    b.Navigation("MoveEventsTo");

                    b.Navigation("Placements");

                    b.Navigation("ScenarioObjectives");

                    b.Navigation("ScenarioUnits");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ObstacleType", b =>
                {
                    b.Navigation("HexFeatures");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Scenario", b =>
                {
                    b.Navigation("ScenarioObjectives");

                    b.Navigation("ScenarioUnits");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.ScenarioObjective", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Session", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("MoveEvents");

                    b.Navigation("ObjectiveLogs");

                    b.Navigation("Placements");

                    b.Navigation("TouchEvents");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Side", b =>
                {
                    b.Navigation("HexFeatures");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Turn", b =>
                {
                    b.Navigation("MoveEvents");

                    b.Navigation("ObjectiveLogs");

                    b.Navigation("Placements");
                });

            modelBuilder.Entity("WargameBoard.Core.Entities.Unit", b =>
                {
                    b.Navigation("Capability");
                });
#pragma warning restore 612, 618
        }
    }
}
